Move all code to a class, add unit tests, handle multiple pages of milestones and labels
wizaplace/github-to-mysql pull request #4
Opened 2019-04-24 20:35 UTC by williamdes

- Moved all code to a class
- Add unit tests
- Fix to handle multiple pages of milestones and labels (#3)
- Added some properties into composer.json
- Upgraded dependencies
- Improved code by removing hard coded sql insert statements

To review, you can review commit by commit

2019-04-24 20:38 UTC, williamdes commented
Tested using `./github-to-mysql sync --since-forever phpmyadmin/phpmyadmin` since this command would not succeed before this PR, see: #3

2019-04-24 20:41 UTC, williamdes commented
@mnapoli Can you please review my work ?

2019-04-25 06:38 UTC, mnapoli commented
@williamdes I have been removed from this repository and I have no longer rights to maintain it. I don't know if this project is maintained, an option might be to use your own fork.

2019-04-25 06:54 UTC, williamdes commented
cc @jeremy-wizaplace @luxifer

2019-04-25 07:08 UTC, luxifer commented
Neither do I

2019-04-30 05:52 UTC, williamdes commented
@anthHugo?

2019-04-30 06:32 UTC, steevanb commented
We are waiting our CTO to know if we continue to maintain this repository :)

2019-05-10 15:06 UTC, wizacedric requested changes

2019-05-10 15:06 UTC, wizacedric commented on app/data.php
> +class data {
Let's follow a few principles here: 
- uppercase names for classes
- separation of concerns
- useful constructors

I suggest splitting this class in 2, one for database write operations, and one for http fetch operations.

2019-05-10 15:06 UTC, wizacedric commented on composer.json
> +    "name": "github-to-mysql",
```suggestion
    "name": "wizaplace/github-to-mysql",
```

2019-05-10 15:06 UTC, wizacedric commented on composer.json
> +    "license": "UNLICENCED",
```suggestion
    "license": "MIT",
```

2019-05-10 15:09 UTC, wizacedric commented
@williamdes thanks for your work on your PR. These are some very good improvements, but I think you can go a bit further :rocket: .

2019-05-10 15:09 UTC, wizacedric requested changes

2019-05-10 15:09 UTC, wizacedric commented on composer.json
> +    "type": "library",
```suggestion
    "type": "project",
```

2019-05-11 23:26 UTC, williamdes commented
@wizacedric I improved this PR using some of your principles
> I suggest splitting this class in 2, one for database write operations, and one for http fetch operations.

I will maybe do some work on this

2019-05-15 10:22 UTC, williamdes commented
@wizacedric Would you accept to merge this PR ?

2019-06-16 17:45 UTC, williamdes commented
@wizagael can you please review my PR?

2019-07-02 09:50 UTC, williamdes commented
cc @wizacedric ..
I invested a lot of my free time, please review or merge

2019-07-02 11:18 UTC, wizacedric approved these changes

2019-07-02 11:20 UTC, merged